import { useState } from "react";
import PromptForm from "./components/PromptForm";
import CodeOutput from "./components/CodeOutput";
import FeedbackForm from "./components/FeedbackForm";
import SnippetList from "./components/SnippetList";
import { toast } from "react-hot-toast";

function App() {
  const [aiCode, setAiCode] = useState("");
  const [currentPrompt, setCurrentPrompt] = useState("");
  const [language, setLanguage] = useState("");
  const [loading, setLoading] = useState(false);
  const handlePromptSubmit = async (prompt, lang) => {
  if (!prompt.trim()) {
    toast.error("Please enter a valid prompt.");
    return;
  }

  setCurrentPrompt(prompt);
  setLanguage(lang);
  setLoading(true);
  toast.loading("⏳ Generating code...");

  try {
    const response = await fetch("http://localhost:5000/api/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ prompt, language: lang }),
    });

    const data = await response.json();

    if (response.ok) {
      setAiCode(data.aiCode);
      toast.dismiss();
      toast.success("✅ Code generated by OpenAI!");
    } else {
      toast.dismiss();
      toast.error("❌ Error: " + data.error);
    }
  } catch (err) {
    toast.dismiss();
    toast.error("❌ Failed to connect to backend");
    console.error(err);
  } finally {
    setLoading(false);
  }
};


  const handleFeedbackSubmit = async (feedback) => {
    if (!feedback.trim()) {
      toast.error("Please write your feedback before submitting.");
      return;
    }

    const payload = {
      prompt: currentPrompt,
      language,
      aiCode,
      userFeedback: feedback,
    };

    try {
      const response = await fetch("http://localhost:5000/api/submit", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      });

      if (response.ok) {
        toast.success("✅ Feedback saved to NeonDB!");
      } else {
        const error = await response.json();
        toast.error("❌ Server error: " + error.error);
      }
    } catch (err) {
      console.error("❌ Submission failed:", err);
      toast.error("❌ Could not connect to backend.");
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-100 to-blue-50 p-6">
      <div className="max-w-4xl mx-auto space-y-8">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-blue-800 drop-shadow-sm">
            CodePromptEval
          </h1>
          <p className="text-gray-600 mt-2">
            Evaluate AI-generated code prompts with human feedback.
          </p>
        </div>

        <PromptForm onSubmit={handlePromptSubmit} />
        {loading && (
          <div className="flex justify-center mt-6">
          <div className="animate-spin rounded-full h-12 w-12 border-t-4 border-blue-500 border-opacity-75"></div>
          </div>
        )}
        {aiCode && <CodeOutput code={aiCode} />}
        {aiCode && <FeedbackForm onSubmit={handleFeedbackSubmit} />}
        <SnippetList />
      </div>
    </div>
  );
}

export default App;
